export enum PageTabs {
  CANVAS_BASIC_ANIMATION = 'CANVAS_BASIC_ANIMATION',
  CANVAS_GAME = 'CANVAS_GAME',
  CANVAS_BAR_CHART = 'CANVAS_ANTV_REPLICATE',
};

export enum EAntLogoState {
  INIT = 'INIT',
  EXPAND = 'EXPAND',
  BOUNCE = 'BOUNCE',
};
