export enum PageTabs {
  CANVAS_INTERACTIVE = 'CANVAS_INTERACTIVE',
  CANVAS_ANALYTICS = 'CANVAS_ANALYTICS',
  GSAP_INTERACTIVE = 'GSAP_INTERACTIVE',
  GSAP_MOTIONS_POPUP = 'GSAP_MOTIONS_POPUP',
  GSAP_MOTIONS_PAGES = 'GSAP_MOTIONS_PAGES',
  LOTTIEFILES = 'LOTTIEFILES',
};

export type Vector2D = {
  x: number;
  y: number;
};
